# Generated by Django 4.1.2 on 2022-10-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Page divers', 'verbose_name_plural': 'Page divers'},
        ),
    ]
