# Generated by Django 4.1.2 on 2022-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_alter_flexpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
