# Generated by Django 4.1.2 on 2022-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_alter_flexpage_options_remove_flexpage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Labore numquam adipisci etincidunt. Numquam labore voluptatem ipsum voluptatem porro. Adipisci porro velit voluptatem modi. Sed quisquam velit non dolorem magnam ipsum adipisci. Non voluptatem magnam non. Magnam sit magnam tempora dolore ipsum. Quisquam porro tempora adipisci labore consectetur adipisci. Ut dolorem voluptatem dolore tempora neque. Non modi dolorem dolorem aliquam. Etincidunt ipsum sed dolore neque ut magnam.', max_length=600, null=True),
        ),
    ]
