# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Quiquia amet etincidunt quisquam. Aliquam labore tempora neque dolorem. Ipsum ipsum labore quisquam est numquam dolor aliquam. Dolore quisquam numquam non. Dolor voluptatem modi modi modi velit modi. Consectetur non consectetur eius. Etincidunt ut sit voluptatem dolor quaerat. Velit velit numquam labore. Velit numquam sed quiquia dolore porro. Amet velit aliquam velit magnam.', max_length=600, null=True),
        ),
    ]
