# Generated by Django 4.1.2 on 2022-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Tempora voluptatem quiquia modi est etincidunt dolor ut. Quiquia porro est ut. Consectetur quaerat quaerat quisquam. Magnam dolorem sit tempora consectetur consectetur etincidunt ipsum. Aliquam adipisci sit ipsum quisquam. Labore neque dolorem quiquia consectetur non etincidunt. Porro tempora sit voluptatem adipisci sit. Aliquam adipisci quisquam dolore numquam magnam. Numquam sit tempora tempora ut velit labore.', max_length=600, null=True),
        ),
    ]
