# Generated by Django 4.1.2 on 2022-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Dolor dolorem sit ipsum ipsum modi modi tempora. Tempora eius magnam velit. Dolorem neque sit dolor sed etincidunt tempora voluptatem. Magnam amet modi voluptatem voluptatem labore modi. Neque dolorem quaerat est quiquia dolor amet. Quaerat dolore magnam adipisci velit. Dolore tempora quiquia consectetur sit. Adipisci quisquam adipisci ipsum numquam. Etincidunt sed modi magnam sit etincidunt dolore neque. Est adipisci sit velit voluptatem eius quaerat.', max_length=600, null=True),
        ),
    ]
