# Generated by Django 4.1.2 on 2022-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0008_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Ut neque numquam ut. Dolor voluptatem tempora etincidunt. Magnam numquam etincidunt dolorem labore quaerat dolorem. Consectetur tempora voluptatem voluptatem eius velit. Numquam dolore est consectetur amet est aliquam aliquam. Labore modi quiquia ipsum magnam etincidunt. Etincidunt dolor porro dolor. Adipisci adipisci non dolor porro. Quaerat eius tempora sit aliquam sit consectetur.', max_length=600, null=True),
        ),
    ]
