# Generated by Django 4.1.2 on 2022-10-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0009_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Eius sed non voluptatem consectetur labore. Consectetur dolorem ut sit. Consectetur dolorem dolorem aliquam. Modi labore eius voluptatem etincidunt. Dolorem etincidunt non sed.', max_length=600, null=True),
        ),
    ]
