# Generated by Django 4.1.2 on 2022-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0010_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Est consectetur amet neque. Numquam tempora neque dolore. Dolore dolor modi dolor ipsum non sed non. Numquam est dolore ut magnam aliquam. Porro sed aliquam ut. Aliquam aliquam consectetur dolor quaerat. Quiquia etincidunt sed quisquam quisquam ut ut quiquia. Velit dolore sit porro neque quaerat labore. Sed numquam modi sit adipisci modi ut.', max_length=600, null=True),
        ),
    ]
