# Generated by Django 4.1.2 on 2022-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0011_alter_flexpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='text',
            field=models.TextField(blank=True, default='Magnam tempora dolor magnam quisquam. Dolor non modi est magnam adipisci modi. Est sed velit sit. Sed quisquam etincidunt modi. Dolorem sit dolorem sed quiquia.', max_length=600, null=True),
        ),
    ]
